### ISSUE TITLE
sysmalloc: assertion failed

### ISSUE THREAD

**Issue by tornaria** [assaferan/omf5#26]
I was able to compile and run `bin/omf5 -tests` works ok.

However:
```
$ bin/omf5 -quad=1,0,0,1,1,1,0,1,0,1,0,0,1,0,8 -format=GG
omf5: malloc.c:2394: sysmalloc: Assertion `(old_top == initial_top (av) && old_size == 0) || ((unsigned long) (old_size) >= MINSIZE && prev_inuse (old_top) && ((unsigned long) old_end & (pagesize - 1)) == 0)' failed.
Aborted
```

Same thing happens with gcc-10 and clang-12, also if I give `-prec` or `-form_idx` parameters.

I'm not sure if the quadratic form is ok, I took the coefficients for discriminant 61 from http://www.cmat.edu.uy/cnt/omf5/qf5_squarefree.txt:
```
...
[61, 61, [1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 8]],
...
```

I have no idea what is `sysmalloc`.

Maybe you could add some examples to the README.md, to have a few sample command lines (to copy and paste) and to see sample output?

@assaferan

**Comment by assaferan** [comment]
@tornaria Thanks for catching this! 
Your input is completely fine, I now added these examples in the README file.
This run was only tested on macOS before, and the above error is due to a buffer overflow when parsing the command-line arguments.
This should be fixed now (in commit 11a6505196e8d2cc75f96d0b9b11149c748b635f).
